# --- filepath: video_narrative_processor/core/repository/base.py
from typing import Protocol, Iterable
from core.models.narrative import VideoNarrative

class RepositoryProtocol(Protocol):
    def save(self, item: VideoNarrative) -> None: ...
    def update(self, item: VideoNarrative) -> None: ...
    def list(self, **filters) -> Iterable[VideoNarrative]: ...
